### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by flakowarhol** [ytisf/theZoo#200]
Hi there, I have this issue, Itried to install but still get this error, can someone help me? thanks

Traceback (most recent call last):
  File "/home/flakowarhol/Downloads/theZoo-master/./theZoo.py", line 109, in <module>
    main()
  File "/home/flakowarhol/Downloads/theZoo-master/./theZoo.py", line 73, in main
    eulaHandler.prompt_eula()
  File "/home/flakowarhol/Downloads/theZoo-master/imports/eula_handler.py", line 54, in prompt_eula
    eula_answer = raw_input(
NameError: name 'raw_input' is not defined

**Comment by SVFs0ciety** [comment]
Hi.you need to rename the line to imports/eula_handler.py line 54 raw_input to input

**Comment by Entity-666** [comment]
> Hi.you need to rename the line imports/eula_handler.py line 54 raw_input to input

Hey, thanks for the help but how do I do that?
