### ISSUE TITLE
theZoo works for windows?

### ISSUE THREAD

**Issue by juliom-meras** [ytisf/theZoo#208]
I'm trying to run theZoo on windows 10, but I get this error, about readline module:

C:\Users\Julio\python theZoo.py

Required modulepython theZoo.py
Required module not installed: readline
Attempting to install with pip...
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

Collecting readline
  Using cached readline-6.2.4.1.tar.gz (2.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: this module is not meant to work on Windows
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "C:\Users\Julio\theZoo\imports\terminal_handler.py", line 5, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Julio\theZoo\imports\terminal_handler.py", line 8, in <module>
    from imports import winreadline as readline
  File "C:\Users\Julio\theZoo\imports\winreadline.py", line 31, in <module>
    import sys, os, msvcrt, _rlsetup
ModuleNotFoundError: No module named '_rlsetup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Julio\theZoo\theZoo.py", line 28, in <module>
    from imports.terminal_handler import Controller
  File "C:\Users\Julio\theZoo\imports\terminal_handler.py", line 19, in <module>
    import readline
ModuleNotFoundError: No module named 'readline' not installed: readline

theZoo works for windows?

Thanks

**Comment by Masato-929** [comment]
you can may open theZoo with "pyreadline" when you use WIndows10. Maybe we cant use readline with Windows.
