### ISSUE TITLE
`update-db` command error 'cannot update'

### ISSUE THREAD

**Issue by MiChaelinzo** [ytisf/theZoo#212]
```
Traceback (most recent call last):
  File "/home/michael/ㄒㄖㄖㄥ丂/theZoo/theZoo.py", line 109, in <module>
    main()
  File "/home/michael/ㄒㄖㄖㄥ丂/theZoo/theZoo.py", line 104, in main
    terminalHandler.MainMenu()
  File "/home/michael/ㄒㄖㄖㄥ丂/theZoo/imports/terminal_handler.py", line 91, in MainMenu
    self.actOnCommand(cmd)
  File "/home/michael/ㄒㄖㄖㄥ丂/theZoo/imports/terminal_handler.py", line 120, in actOnCommand
    db_ver = update_handler.get_maldb_ver()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/ㄒㄖㄖㄥ丂/theZoo/imports/update_handler.py", line 46, in get_maldb_ver
    with file(globals.vars.maldb_ver_file) as f:
         ^^^^
NameError: name 'file' is not defined. Did you mean: 'filter'?

```

**Comment by BumblingBen** [comment]
Not an actual bug. I had the same issue when running using python3.

You need to ensure python2.7 is installed, I can't seem to see this within the ReadMe or the requirements docs, correct me if I'm wrong. So you'll need to do the following:

**Install the correct version of Python**
`sudo apt install python2.7`

**Explicitly run the script using version 2.7**
`python2.7 theZoo.py`

**Comment by MiChaelinzo** [comment]
> Not an actual bug. I had the same issue when running using python3.
> 
> You need to ensure python2.7 is installed, I can't seem to see this within the ReadMe or the requirements docs, correct me if I'm wrong. So you'll need to do the following:
> 
> **Install the correct version of Python**
> `sudo apt install python2.7`
> 
> **Explicitly run the script using version 2.7**
> `python2.7 theZoo.py`
> 
> 
> 

Alright thanks I still have python2 in my ParrotOS

**Comment by mrhenrike** [comment]
**Update from PR [#243](https://github.com/ytisf/theZoo/pull/243):** Fixed in PR#243 — update_handler.py now strips the version string before comparison (trailing newline was causing false 'up to date' reports). Table name corrected to Malwares.
