### ISSUE TITLE
[Win10] ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by pmeirelesf** [ytisf/theZoo#84]
I am trying to run theZoo in Windows 10/Python 2.7.14, but I always got this error:

> C:\theZoo>python theZoo.py
> Traceback (most recent call last):
>   File "theZoo.py", line 28, in <module>
>     from imports.terminal_handler import Controller
>   File "C:\theZoo\imports\terminal_handler.py", line 7, in <module>
>     from imports import winreadline as readline
>   File "C:\theZoo\imports\winreadline.py", line 31, in <module>
>     import sys, os, msvcrt, _rlsetup
> ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by ytisf** [comment]
Hey @pmeirelesf .This seems more like a Windows&Python issue. Have a look[here](https://stackoverflow.com/questions/19019720/importerror-dll-load-failed-1-is-not-a-valid-win32-application-but-the-dlls). If this does not solve it for you, load a Python console and post the output of this here:
`import msvcrt
print msvcrt.__version__`

**Comment by GitHub-zd** [comment]
You need to pip install pyreadline     .
